// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    Dialog: typeof import('./src/components/Dialog/Dialog.vue')['default']
    Editor: typeof import('./src/components/Editor/Editor.vue')['default']
    LoadingShade: typeof import('./src/components/LoadingShade/LoadingShade.vue')['default']
    Page: typeof import('./src/components/Page/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
